service: nostr-bots
frameworkVersion: '3'

provider:
  name: aws
  region: ap-northeast-1
  runtime: nodejs18.x
  memorySize: 128
  architecture: arm64
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - ssm:GetParameter
            - kms:Decrypt
          Resource:
            - '*'

functions:
  echo:
    handler: handlers/echo.handler
    layers:
      - arn:aws:lambda:ap-northeast-1:133490724326:layer:AWS-Parameters-and-Secrets-Lambda-Extension-Arm64:2
    events:
      - httpApi:
          path: /echo
          method: post
  mahjong:
    handler: handlers/mahjong.handler
    layers:
      - arn:aws:lambda:ap-northeast-1:133490724326:layer:AWS-Parameters-and-Secrets-Lambda-Extension-Arm64:2
    events:
      - httpApi:
          path: /mahjong
          method: post
  dice:
    handler: handlers/dice.handler
    layers:
      - arn:aws:lambda:ap-northeast-1:133490724326:layer:AWS-Parameters-and-Secrets-Lambda-Extension-Arm64:2
    events:
      - httpApi:
          path: /dice
          method: post
  sushiyuki:
    handler: handlers/sushiyuki.handler
    layers:
      - arn:aws:lambda:ap-northeast-1:133490724326:layer:AWS-Parameters-and-Secrets-Lambda-Extension-Arm64:2
    events:
      - httpApi:
          path: /sushiyuki
          method: post
  req:
    handler: handlers/req.handler
    layers:
      - arn:aws:lambda:ap-northeast-1:133490724326:layer:AWS-Parameters-and-Secrets-Lambda-Extension-Arm64:2
    events:
      - httpApi:
          path: /req
          method: post
    timeout: 15
  search:
    handler: handlers/search.handler
    layers:
      - arn:aws:lambda:ap-northeast-1:133490724326:layer:AWS-Parameters-and-Secrets-Lambda-Extension-Arm64:2
    events:
      - httpApi:
          path: /search
          method: post
    timeout: 15
  random_image_register:
    handler: handlers/random_image.register
    layers:
      - arn:aws:lambda:ap-northeast-1:133490724326:layer:AWS-Parameters-and-Secrets-Lambda-Extension-Arm64:2
    events:
      - httpApi:
          path: /random_image/register
          method: post
    timeout: 15
  random_image_draw:
    handler: handlers/random_image.draw
    layers:
      - arn:aws:lambda:ap-northeast-1:133490724326:layer:AWS-Parameters-and-Secrets-Lambda-Extension-Arm64:2
    events:
      - httpApi:
          path: /random_image/draw
          method: post
    timeout: 15
